export const GameConfig = {
  // Game settings
  INITIAL_LIVES: 3,
  FREE_LIFE_SCORE_INTERVAL: 10000,
  
  // Player settings
  PLAYER_TURN_SPEED: 75, // VALOR CORRETO DO ORIGINAL (era 200!)
  PLAYER_FUEL_INCREASE_RATE: 30,
  PLAYER_FUEL_BURN_RATE: 5,
  PLAYER_MAX_FUEL: 100,
  
  // River settings
  RIVER_MIN_SPEED: 75, // VALOR CORRETO DO ORIGINAL
  RIVER_DEFAULT_SPEED: 150, // VALOR CORRETO DO ORIGINAL
  RIVER_MAX_SPEED: 500, // VALOR CORRETO DO ORIGINAL
  RIVER_SPEED_SENSITIVITY: 125, // VALOR CORRETO DO ORIGINAL
  
  // Bullet settings
  BULLET_SPEED: 750, // VALOR CORRETO DO ORIGINAL
  
  // River generation
  TILE_SIZE: 8,
  MAP_WIDTH: 60,  // 480px / 8px
  MAP_HEIGHT: 96, // 768px / 8px
  MINIMUM_RIVER_WIDTH: 5, // VALOR CORRETO DO ORIGINAL
  INITIAL_LINES_WITHOUT_CHANGE: 15, // VALOR CORRETO DO ORIGINAL
  
  // Spawn rates (0-100)
  ENEMY_SPAWN_RATE: 17, // VALOR CORRETO DO ORIGINAL
  FUEL_DEPOT_SPAWN_RATE: 7, // VALOR CORRETO DO ORIGINAL
  FUEL_DEPOT_SPAWN_COOLDOWN: 7, // VALOR CORRETO DO ORIGINAL
  
  // Enemy settings
  HELICOPTER_MIN_SPEED: 50,
  HELICOPTER_MAX_SPEED: 100,
  HELICOPTER_SCORE: 100,
  
  JET_MIN_SPEED: 150,
  JET_MAX_SPEED: 200,
  JET_SCORE: 200,
  
  TANKER_MIN_SPEED: 30,
  TANKER_MAX_SPEED: 60,
  TANKER_SCORE: 150,
  
  FUEL_DEPOT_SCORE: 80,
  
  // HUD settings
  FUEL_WARNING_THRESHOLD: 25,
  
  // Timers
  GET_READY_DURATION: 2000,
  PAUSE_AFTER_CRASH_DURATION: 3000,
  FUEL_WARNING_INTERVAL: 1000
};

export const BankDirection = {
  LEFT: 'turnleft',
  STRAIGHT: 'straight',
  RIGHT: 'turnright'
};
